version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:80"
    environment:
      - APP_ENV=production
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - ./logs:/var/www/html/logs

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: 